# Server configuration
server:
  port: 8080

spring:
  application:
    name: blog

  datasource:
    url: jdbc:mysql://localhost:3306/blogs
    username: root
    password: rootuser
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    ddl-auto: update
    show-sql: true
    properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret:
    key: J1pUaSLrDyiUeMfKMHsNLkRKtkSxrV167mCeGmigTwc= #base64encoded
  expiry:
    time: 86400000
